# fly.toml app configuration file generated for optima on 2025-04-27T20:33:26+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'optima'
primary_region = 'hkg'
console_command = '/manage.py shell'

[build]

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = "shared-cpu-1x"


[[statics]]
  guest_path = '/static'
  url_prefix = '/static/'

[deploy]
  release_command = "python manage.py migrate"
  command = "gunicorn config.wsgi:application --bind 0.0.0.0:8000"
