# Generated by Django 5.1.6 on 2025-02-19 15:03

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=255)),
                ('throat_standard', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Стандарт горла')),
                ('throat_diameter', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Диаметр горла (мм)')),
                ('package_volume', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Объем (литров)')),
                ('dimensions', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Габариты (ДхШ стенки (мм))')),
                ('compound', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Состав')),
                ('basic_lighting_solution', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Базовый световой решение')),
                ('material', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Материал')),
                ('package', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Упаковка')),
                ('weight', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Вес (г)')),
                ('application', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Применение')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images/', verbose_name='Изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
