# Generated by Django 5.1.6 on 2025-02-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='type',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='ctagory_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type',
            name='type_name',
            field=models.CharField(default=2, max_length=255, verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
