# Generated by Django 5.1.6 on 2025-02-20 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0008_remove_user_login_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='ctagory_name',
            new_name='category_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='product',
            name='application',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Применение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='compound',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Габариты (ДхШ стенки (мм))'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='package',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Упаковка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='package_volume',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Объем (литров)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='throat_diameter',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Диаметр горла (мм)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='throat_standard',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Стандарт горла'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес (г)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=1, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
