# Generated by Django 5.1.6 on 2025-02-21 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_ctagory_name_category_category_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
