# Generated by Django 5.1.6 on 2025-02-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_type_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
